project:
  type: website
  output-dir: ../docs

website:
  title: "Programming Cafe"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - agenda.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



